// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehousePro.API.Data;

#nullable disable

namespace Warehousepro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehousePro.API.Models.AuditLog", b =>
                {
                    b.Property<int>("AuditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("AuditID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("WarehousePro.API.Models.BinLocation", b =>
                {
                    b.Property<int>("BinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BinID"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("BinID");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ZoneID");

                    b.ToTable("BinLocations");
                });

            modelBuilder.Entity("WarehousePro.API.Models.InboundReceipt", b =>
                {
                    b.Property<int>("ReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ReceiptID");

                    b.ToTable("InboundReceipts");
                });

            modelBuilder.Entity("WarehousePro.API.Models.InventoryBalance", b =>
                {
                    b.Property<int>("BalanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BalanceID"));

                    b.Property<int>("BinID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("int");

                    b.HasKey("BalanceID");

                    b.HasIndex("BinID");

                    b.HasIndex("ItemID", "BinID")
                        .IsUnique();

                    b.ToTable("InventoryBalances");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ItemID");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PackingUnit", b =>
                {
                    b.Property<int>("PackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackID"));

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PackedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("PackID");

                    b.HasIndex("OrderID");

                    b.ToTable("PackingUnits");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PickTask", b =>
                {
                    b.Property<int>("PickTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PickTaskID"));

                    b.Property<int?>("AssignedToUserID")
                        .HasColumnType("int");

                    b.Property<int>("BinID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("PickQuantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PickTaskID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("BinID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("PickTasks");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PutAwayTask", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int?>("AssignedToUserID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetBinID")
                        .HasColumnType("int");

                    b.HasKey("TaskID");

                    b.HasIndex("AssignedToUserID");

                    b.HasIndex("ItemID");

                    b.HasIndex("ReceiptID");

                    b.HasIndex("TargetBinID");

                    b.ToTable("PutAwayTasks");
                });

            modelBuilder.Entity("WarehousePro.API.Models.ReplenishmentTask", b =>
                {
                    b.Property<int>("ReplenishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplenishID"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromBinID")
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToBinID")
                        .HasColumnType("int");

                    b.HasKey("ReplenishID");

                    b.HasIndex("FromBinID");

                    b.HasIndex("ItemID");

                    b.HasIndex("ToBinID");

                    b.ToTable("ReplenishmentTasks");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShipmentID"));

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ShipmentID");

                    b.HasIndex("OrderID");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("WarehousePro.API.Models.SlottingRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Criterion")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.ToTable("SlottingRules");
                });

            modelBuilder.Entity("WarehousePro.API.Models.StockReservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceID")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("ItemID");

                    b.ToTable("StockReservations");
                });

            modelBuilder.Entity("WarehousePro.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("WarehouseID");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("WarehousePro.API.Models.WarehouseReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<int>("GeneratedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("GeneratedByUserID");

                    b.ToTable("WarehouseReports");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int");

                    b.Property<int>("ZoneType")
                        .HasColumnType("int");

                    b.HasKey("ZoneID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("WarehousePro.API.Models.AuditLog", b =>
                {
                    b.HasOne("WarehousePro.API.Models.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarehousePro.API.Models.BinLocation", b =>
                {
                    b.HasOne("WarehousePro.API.Models.Zone", "Zone")
                        .WithMany("BinLocations")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("WarehousePro.API.Models.InventoryBalance", b =>
                {
                    b.HasOne("WarehousePro.API.Models.BinLocation", "BinLocation")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("BinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.Item", "Item")
                        .WithMany("InventoryBalances")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BinLocation");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Notification", b =>
                {
                    b.HasOne("WarehousePro.API.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PackingUnit", b =>
                {
                    b.HasOne("WarehousePro.API.Models.Order", "Order")
                        .WithMany("PackingUnits")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PickTask", b =>
                {
                    b.HasOne("WarehousePro.API.Models.User", "AssignedTo")
                        .WithMany("PickTasks")
                        .HasForeignKey("AssignedToUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WarehousePro.API.Models.BinLocation", "BinLocation")
                        .WithMany("PickTasks")
                        .HasForeignKey("BinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.Item", "Item")
                        .WithMany("PickTasks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.Order", "Order")
                        .WithMany("PickTasks")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("BinLocation");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WarehousePro.API.Models.PutAwayTask", b =>
                {
                    b.HasOne("WarehousePro.API.Models.User", "AssignedTo")
                        .WithMany("PutAwayTasks")
                        .HasForeignKey("AssignedToUserID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WarehousePro.API.Models.Item", "Item")
                        .WithMany("PutAwayTasks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.InboundReceipt", "InboundReceipt")
                        .WithMany("PutAwayTasks")
                        .HasForeignKey("ReceiptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.BinLocation", "TargetBin")
                        .WithMany("PutAwayTasks")
                        .HasForeignKey("TargetBinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("InboundReceipt");

                    b.Navigation("Item");

                    b.Navigation("TargetBin");
                });

            modelBuilder.Entity("WarehousePro.API.Models.ReplenishmentTask", b =>
                {
                    b.HasOne("WarehousePro.API.Models.BinLocation", "FromBin")
                        .WithMany("ReplenishFromTasks")
                        .HasForeignKey("FromBinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.Item", "Item")
                        .WithMany("ReplenishmentTasks")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WarehousePro.API.Models.BinLocation", "ToBin")
                        .WithMany("ReplenishToTasks")
                        .HasForeignKey("ToBinID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromBin");

                    b.Navigation("Item");

                    b.Navigation("ToBin");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Shipment", b =>
                {
                    b.HasOne("WarehousePro.API.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WarehousePro.API.Models.StockReservation", b =>
                {
                    b.HasOne("WarehousePro.API.Models.Item", "Item")
                        .WithMany("StockReservations")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("WarehousePro.API.Models.WarehouseReport", b =>
                {
                    b.HasOne("WarehousePro.API.Models.User", "GeneratedBy")
                        .WithMany("WarehouseReports")
                        .HasForeignKey("GeneratedByUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Zone", b =>
                {
                    b.HasOne("WarehousePro.API.Models.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehousePro.API.Models.BinLocation", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("PickTasks");

                    b.Navigation("PutAwayTasks");

                    b.Navigation("ReplenishFromTasks");

                    b.Navigation("ReplenishToTasks");
                });

            modelBuilder.Entity("WarehousePro.API.Models.InboundReceipt", b =>
                {
                    b.Navigation("PutAwayTasks");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Item", b =>
                {
                    b.Navigation("InventoryBalances");

                    b.Navigation("PickTasks");

                    b.Navigation("PutAwayTasks");

                    b.Navigation("ReplenishmentTasks");

                    b.Navigation("StockReservations");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Order", b =>
                {
                    b.Navigation("PackingUnits");

                    b.Navigation("PickTasks");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("WarehousePro.API.Models.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");

                    b.Navigation("PickTasks");

                    b.Navigation("PutAwayTasks");

                    b.Navigation("WarehouseReports");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Warehouse", b =>
                {
                    b.Navigation("Zones");
                });

            modelBuilder.Entity("WarehousePro.API.Models.Zone", b =>
                {
                    b.Navigation("BinLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
